### PR TITLE
Cursor set to pointer for .homepage-form-box

### PR DESCRIPTION
**Pull request by only4arman**
Added
```CSS
.homepage-form-box {
  cursor: pointer;
}
```
in theme.css

Issue #10

### CODE REVIEW

**Comment by mbad0la** [comment]
@prabhakar267 please assign "invalid" label to this PR

@only4arman do take note that the issue has been claimed by me and it is not in the spirit of contribution to cut in like this

**Comment by only4arman** [comment]
Did you find any problem in the code that you want it mark it as invalid. 
If not then why?

I submitted a pull request because it was opened and not a single request was there.

If you have claimed it then where is your PR.
It was not an arduous task to set cursor to pointer.

**Comment by geekfred** [comment]
@only4arman not trying to get into an issue that I'm not participating in but the idea of this contributions is that there's also developers that are learning and trying to contribute, maybe it is easy for you to set cursor to pointer, but maybe not so much for a beginner, the idea is to be polite and ask if the issue has been assigned already. Just saying.

**Comment by only4arman** [comment]
Open source means anyone can contribute to it and it doesn't mean if it is assigned to someone then others can't do it.
I just submitted a PR because no one had. Nothing more.
If the owner like it then he would have merge it. But do you see mine one merged. Nope.
But he's. Yes.

One more thing, he is not a beginner. He have grad. degree in CS.

**Comment by geekfred** [comment]
@only4arman yeah, just my opinion man. I just ask first before getting into it. Have a great weekend!

**Comment by mbad0la** [comment]
> Open source means anyone can contribute to it and it doesn't mean if it is assigned to someone then others can't do it

Sure @only4arman , but that is why you can fork the repository and make changes there. You don't just raise a PR out of the blue as it adds onto the effort the maintainer has to put in. The correct flow to contributions is you pick an issue and check if it's not claimed by anyone (and then ping the maintainer that you're claiming it)

It's not about the speed with which you roll-out a contribution. **It's about the intent to contribute**.

Open Source doesn't have to be chaotic. Keep it organised! 😄 

As for the "invalid" label comment, it's for making sure the hacktoberfest folks don't pick this up as a contribution. You wouldn't want to cheat now would you?

@geekfred thanks for taking out time to be a part of this thread. As a part of open source community, it is our responsibility to follow and maintain a code of conduct and on-board people onto it. Really appreciate it!

**Pull request closed without merging**
